### ISSUE TITLE
Performance of foreach vs indexed loops

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/NFBugs#31]
What is the source for the comparison here [https://github.com/ualberta-smr/NFBugs/blob/master/java-data/Glazed/problems/general-practise/1/problem.yml](https://github.com/ualberta-smr/NFBugs/blob/master/java-data/Glazed/problems/general-practise/1/problem.yml) ?

**Comment by aradu12** [comment]
See [this article](https://dzone.com/articles/iteration-over-java-collections-with-high-performa), under the **forEach vs. C Style vs. Stream API** header. They do a performance test and explain how foreach tends to be slower because it has to create an iterator and call hasNext().

Also here is another performance test from a different source: [link](https://howtodoinjava.com/java/collections/performance-comparison-of-different-for-loops-in-java/)

**Comment by snadi** [comment]
Thanks!
