### ISSUE TITLE
General advise does not make sense

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/NFBugs#48]
The general advise [here](https://github.com/ualberta-smr/NFBugs/blob/master/py-data/BBS/problems/general-practise/2/problem.yml) does not make sense. Isn't this a type of attack? Why would it be allowed? Can you maybe explain what changes in the code are relevant here and how they help avoid the attach?

**Comment by aradu12** [comment]
yes, unfortunately the type of attack has the same name as the protection (csrf and csrf token respectively). I edited the wording to make the distinction more clear. 
See the heading "token based mitigation" [here](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet) and also the [wiki](https://en.wikipedia.org/wiki/Cross-site_request_forgery)

Basically each request in a browser session needs a unique token so that only authorized user requests are permitted.
